version: '3.4'

networks:
    myAppNetwork:  

services:
    SqlServerDb:
        container_name: SqlServerContainer
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - 8002:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=myStong_Password123#
            - Logger:FilePath=//logs//logs.txt
    retailprocurementsystem:
        image: ${DOCKER_REGISTRY-}retailprocurementsystem
        build:
            context: .
            dockerfile: RetailProcurementSystem/Dockerfile
        depends_on:
            - SqlServerDb
